Not working
Guitaryuga/LearnPython-E-learn-project pull request #2
Opened 2020-12-30 18:00 UTC by Guitaryuga

Появляется ошибка типа:
AttributeError: type object 'Course' has no attribute '_sa_instance_state'
...
sqlalchemy.orm.exc.UnmappedInstanceError: Class 'flask_sqlalchemy.model.DefaultMeta' is not mapped; was a class (webapp.model.Course) supplied where an instance was required?

2021-01-05 23:22 UTC, VorontsovIE requested changes
Отметил то, что мне кажется ошибкой.

2021-01-05 23:22 UTC, VorontsovIE commented on webapp/database.py
> +    Course.lessons = ['1', '2']   # Для сохранения ассоциаций решил подставить код в эту функцию
Вот здесь проблема. 
(а) Ты должен сохранять уроки ведь в конкретный курс, а не в класс Course
(б) Ты в lessons должен записывать не строки и не числа, а сами  уроки, т.е. объекты типа Lesson. Т.е. тут больше подойдёт что-то вроде new new_course.lessons = [Lesson.query.get(1), Lesson.query.get(2)]
(в) А почему вообще здесь фиксированные id уроков?

2021-01-05 23:22 UTC, VorontsovIE commented on webapp/model.py
> +    __tablename__ = 'Course'
Мне кажется, эти строки лишние, такое имя таблицы по имени класса автоматически будет выведено. Впрочем, это и не мешает.

2021-01-05 23:22 UTC, VorontsovIE commented on webapp/model.py
> +    material = db.Column(db.Text, nullable=True)
В дальнейшем можно будет сделать таблицу material_types и давать описание не текстом, а номером типа материала в этой таблице.

2021-01-05 23:22 UTC, VorontsovIE commented on webapp/__init__.py
> +        return render_template('signin.html', page_title = title, form= login_form)
А где сами шаблоны? Их в коммите нет

2021-01-06 21:55 UTC, Guitaryuga commented on webapp/__init__.py
> +        return render_template('signin.html', page_title = title, form= login_form)
Так как функционал логина временно отключили, то решил их не включать, поскольку основная проблема все еще с базой данных

2021-01-06 22:31 UTC, Guitaryuga commented on webapp/database.py
> +    Course.lessons = ['1', '2']   # Для сохранения ассоциаций решил подставить код в эту функцию
Фиrсированные id в 49 строке - это моя попытка разобраться, как ведет себя код и база данных при записи и что куда идёт.
Т.е я правильно понимаю, что по идее следуя заданной мной модели в таблице Course у меня должен появиться отдельный столбец lessons, куда и должны вноситься объекты типа Lesson?

2021-01-06 22:38 UTC, VorontsovIE commented on webapp/database.py
> +    Course.lessons = ['1', '2']   # Для сохранения ассоциаций решил подставить код в эту функцию
Нет. SQLAlchemy автоматом понимает, что когда ты присваиваешь уроки в поле lessons, надо сохранять эти данные в таблицу-связку course_lessons (не помню точно её название). А в таблицы lessons и courses при этом ничего не сохраняется, кроме описания самого курса/урока. Эти таблицы ничего не знают друг про друга, вся связь работает на уровне класса модели, где прописана ассоциация.
Бывают ещё связи one-to-many, они устроены немного по-другому: там у урока была бы ссылка на родительский курс. И при сохранении course.lessons = [...] у тебя информация на самом деле обновлялась бы не в таблице курса (там вообще ничего про уроки не пишется), а в таблице урока (там есть поле course_id, которое обновилось бы).

2021-01-07 17:35 UTC, Guitaryuga commented on webapp/database.py
> +    Course.lessons = ['1', '2']   # Для сохранения ассоциаций решил подставить код в эту функцию
Тогда выходит в первую очередь в базу данных вносятся Lessons, а дальше мне нужна функция, которая определит, с каким id вносится курс в Courses и на основе этого из списка со словарями lessons_to_courses выбираются те уроки, у которых указан id курса?
А может тогда проще изначально иметь в источнике данных курса словарь типа { "lessons" : [ '1', '2'...] }, чтобы потом список уроков рендерился на страничке в соответствии с ним?

2021-01-18 15:05 UTC, merged